/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthenticatedAuthorityRouteRouteImport } from './routes/_authenticated/authority/route'
import { Route as AuthenticatedBusinessRouteRouteImport } from './routes/_authenticated/business/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business/index'
import { Route as AuthenticatedBusinessCertificatesRouteImport } from './routes/_authenticated/business/certificates'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business/dashboard'
import { Route as AuthenticatedBusinessInstrumentsRouteImport } from './routes/_authenticated/business/instruments'
import { Route as AuthenticatedBusinessNotificationsRouteImport } from './routes/_authenticated/business/notifications'
import { Route as AuthenticatedBusinessProfileRouteImport } from './routes/_authenticated/business/profile'
import { Route as AuthenticatedBusinessRequestsRouteImport } from './routes/_authenticated/business/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthorityRouteRoute =
  AuthenticatedAuthorityRouteRouteImport.update({
    id: '/authority',
    path: '/authority',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessRouteRoute =
  AuthenticatedBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessCertificatesRoute =
  AuthenticatedBusinessCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessInstrumentsRoute =
  AuthenticatedBusinessInstrumentsRouteImport.update({
    id: '/instruments',
    path: '/instruments',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessNotificationsRoute =
  AuthenticatedBusinessNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessProfileRoute =
  AuthenticatedBusinessProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessRequestsRoute =
  AuthenticatedBusinessRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/authority': typeof AuthenticatedAuthorityRouteRoute
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify/': typeof VerifyIndexRoute
  '/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/authority': typeof AuthenticatedAuthorityRouteRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify': typeof VerifyIndexRoute
  '/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/_authenticated/authority': typeof AuthenticatedAuthorityRouteRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/_authenticated/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/_authenticated/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/_authenticated/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/authority'
    | '/business'
    | '/onboarding'
    | '/verify/$code'
    | '/verify/'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/instruments'
    | '/business/notifications'
    | '/business/profile'
    | '/business/requests'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/authority'
    | '/onboarding'
    | '/verify/$code'
    | '/verify'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/instruments'
    | '/business/notifications'
    | '/business/profile'
    | '/business/requests'
    | '/business'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/_authenticated/authority'
    | '/_authenticated/business'
    | '/_authenticated/onboarding'
    | '/verify/$code'
    | '/verify/'
    | '/_authenticated/business/certificates'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/business/instruments'
    | '/_authenticated/business/notifications'
    | '/_authenticated/business/profile'
    | '/_authenticated/business/requests'
    | '/_authenticated/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authority': {
      id: '/_authenticated/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthenticatedAuthorityRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/certificates': {
      id: '/_authenticated/business/certificates'
      path: '/certificates'
      fullPath: '/business/certificates'
      preLoaderRoute: typeof AuthenticatedBusinessCertificatesRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/instruments': {
      id: '/_authenticated/business/instruments'
      path: '/instruments'
      fullPath: '/business/instruments'
      preLoaderRoute: typeof AuthenticatedBusinessInstrumentsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/notifications': {
      id: '/_authenticated/business/notifications'
      path: '/notifications'
      fullPath: '/business/notifications'
      preLoaderRoute: typeof AuthenticatedBusinessNotificationsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/profile': {
      id: '/_authenticated/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof AuthenticatedBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/requests': {
      id: '/_authenticated/business/requests'
      path: '/requests'
      fullPath: '/business/requests'
      preLoaderRoute: typeof AuthenticatedBusinessRequestsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
  }
}

interface AuthenticatedBusinessRouteRouteChildren {
  AuthenticatedBusinessCertificatesRoute: typeof AuthenticatedBusinessCertificatesRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessInstrumentsRoute: typeof AuthenticatedBusinessInstrumentsRoute
  AuthenticatedBusinessNotificationsRoute: typeof AuthenticatedBusinessNotificationsRoute
  AuthenticatedBusinessProfileRoute: typeof AuthenticatedBusinessProfileRoute
  AuthenticatedBusinessRequestsRoute: typeof AuthenticatedBusinessRequestsRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
}

const AuthenticatedBusinessRouteRouteChildren: AuthenticatedBusinessRouteRouteChildren =
  {
    AuthenticatedBusinessCertificatesRoute:
      AuthenticatedBusinessCertificatesRoute,
    AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
    AuthenticatedBusinessInstrumentsRoute:
      AuthenticatedBusinessInstrumentsRoute,
    AuthenticatedBusinessNotificationsRoute:
      AuthenticatedBusinessNotificationsRoute,
    AuthenticatedBusinessProfileRoute: AuthenticatedBusinessProfileRoute,
    AuthenticatedBusinessRequestsRoute: AuthenticatedBusinessRequestsRoute,
    AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
  }

const AuthenticatedBusinessRouteRouteWithChildren =
  AuthenticatedBusinessRouteRoute._addFileChildren(
    AuthenticatedBusinessRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuthorityRouteRoute: typeof AuthenticatedAuthorityRouteRoute
  AuthenticatedBusinessRouteRoute: typeof AuthenticatedBusinessRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuthorityRouteRoute: AuthenticatedAuthorityRouteRoute,
  AuthenticatedBusinessRouteRoute: AuthenticatedBusinessRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
