/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthenticatedAuthorityRouteRouteImport } from './routes/_authenticated/authority/route'
import { Route as AuthenticatedBusinessRouteRouteImport } from './routes/_authenticated/business/route'
import { Route as AuthenticatedLmoRouteRouteImport } from './routes/_authenticated/lmo/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as VerifyCodeRouteImport } from './routes/verify/$code'
import { Route as AuthenticatedAuthorityIndexRouteImport } from './routes/_authenticated/authority/index'
import { Route as AuthenticatedAuthorityAssignmentsRouteImport } from './routes/_authenticated/authority/assignments'
import { Route as AuthenticatedAuthorityCertificatesRouteImport } from './routes/_authenticated/authority/certificates'
import { Route as AuthenticatedAuthorityDashboardRouteImport } from './routes/_authenticated/authority/dashboard'
import { Route as AuthenticatedAuthorityNotificationsRouteImport } from './routes/_authenticated/authority/notifications'
import { Route as AuthenticatedAuthorityProfileRouteImport } from './routes/_authenticated/authority/profile'
import { Route as AuthenticatedAuthorityQueueRouteImport } from './routes/_authenticated/authority/queue'
import { Route as AuthenticatedAuthoritySmartRouteRouteImport } from './routes/_authenticated/authority/smart-route'
import { Route as AuthenticatedAuthorityVerifyRouteImport } from './routes/_authenticated/authority/verify'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business/index'
import { Route as AuthenticatedBusinessCertificatesRouteImport } from './routes/_authenticated/business/certificates'
import { Route as AuthenticatedBusinessDashboardRouteImport } from './routes/_authenticated/business/dashboard'
import { Route as AuthenticatedBusinessInstrumentsRouteImport } from './routes/_authenticated/business/instruments'
import { Route as AuthenticatedBusinessNotificationsRouteImport } from './routes/_authenticated/business/notifications'
import { Route as AuthenticatedBusinessProfileRouteImport } from './routes/_authenticated/business/profile'
import { Route as AuthenticatedBusinessRequestsRouteImport } from './routes/_authenticated/business/requests'
import { Route as AuthenticatedLmoSmartRouteRouteImport } from './routes/_authenticated/lmo/smart-route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthorityRouteRoute =
  AuthenticatedAuthorityRouteRouteImport.update({
    id: '/authority',
    path: '/authority',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessRouteRoute =
  AuthenticatedBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLmoRouteRoute = AuthenticatedLmoRouteRouteImport.update({
  id: '/lmo',
  path: '/lmo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthorityIndexRoute =
  AuthenticatedAuthorityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityAssignmentsRoute =
  AuthenticatedAuthorityAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityCertificatesRoute =
  AuthenticatedAuthorityCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityDashboardRoute =
  AuthenticatedAuthorityDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityNotificationsRoute =
  AuthenticatedAuthorityNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityProfileRoute =
  AuthenticatedAuthorityProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityQueueRoute =
  AuthenticatedAuthorityQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthoritySmartRouteRoute =
  AuthenticatedAuthoritySmartRouteRouteImport.update({
    id: '/smart-route',
    path: '/smart-route',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedAuthorityVerifyRoute =
  AuthenticatedAuthorityVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => AuthenticatedAuthorityRouteRoute,
  } as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessCertificatesRoute =
  AuthenticatedBusinessCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessDashboardRoute =
  AuthenticatedBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessInstrumentsRoute =
  AuthenticatedBusinessInstrumentsRouteImport.update({
    id: '/instruments',
    path: '/instruments',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessNotificationsRoute =
  AuthenticatedBusinessNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessProfileRoute =
  AuthenticatedBusinessProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessRequestsRoute =
  AuthenticatedBusinessRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedLmoSmartRouteRoute =
  AuthenticatedLmoSmartRouteRouteImport.update({
    id: '/smart-route',
    path: '/smart-route',
    getParentRoute: () => AuthenticatedLmoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/authority': typeof AuthenticatedAuthorityRouteRouteWithChildren
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/lmo': typeof AuthenticatedLmoRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify/': typeof VerifyIndexRoute
  '/authority/assignments': typeof AuthenticatedAuthorityAssignmentsRoute
  '/authority/certificates': typeof AuthenticatedAuthorityCertificatesRoute
  '/authority/dashboard': typeof AuthenticatedAuthorityDashboardRoute
  '/authority/notifications': typeof AuthenticatedAuthorityNotificationsRoute
  '/authority/profile': typeof AuthenticatedAuthorityProfileRoute
  '/authority/queue': typeof AuthenticatedAuthorityQueueRoute
  '/authority/smart-route': typeof AuthenticatedAuthoritySmartRouteRoute
  '/authority/verify': typeof AuthenticatedAuthorityVerifyRoute
  '/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/lmo/smart-route': typeof AuthenticatedLmoSmartRouteRoute
  '/authority/': typeof AuthenticatedAuthorityIndexRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/lmo': typeof AuthenticatedLmoRouteRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify': typeof VerifyIndexRoute
  '/authority/assignments': typeof AuthenticatedAuthorityAssignmentsRoute
  '/authority/certificates': typeof AuthenticatedAuthorityCertificatesRoute
  '/authority/dashboard': typeof AuthenticatedAuthorityDashboardRoute
  '/authority/notifications': typeof AuthenticatedAuthorityNotificationsRoute
  '/authority/profile': typeof AuthenticatedAuthorityProfileRoute
  '/authority/queue': typeof AuthenticatedAuthorityQueueRoute
  '/authority/smart-route': typeof AuthenticatedAuthoritySmartRouteRoute
  '/authority/verify': typeof AuthenticatedAuthorityVerifyRoute
  '/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/lmo/smart-route': typeof AuthenticatedLmoSmartRouteRoute
  '/authority': typeof AuthenticatedAuthorityIndexRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/_authenticated/authority': typeof AuthenticatedAuthorityRouteRouteWithChildren
  '/_authenticated/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/_authenticated/lmo': typeof AuthenticatedLmoRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/authority/assignments': typeof AuthenticatedAuthorityAssignmentsRoute
  '/_authenticated/authority/certificates': typeof AuthenticatedAuthorityCertificatesRoute
  '/_authenticated/authority/dashboard': typeof AuthenticatedAuthorityDashboardRoute
  '/_authenticated/authority/notifications': typeof AuthenticatedAuthorityNotificationsRoute
  '/_authenticated/authority/profile': typeof AuthenticatedAuthorityProfileRoute
  '/_authenticated/authority/queue': typeof AuthenticatedAuthorityQueueRoute
  '/_authenticated/authority/smart-route': typeof AuthenticatedAuthoritySmartRouteRoute
  '/_authenticated/authority/verify': typeof AuthenticatedAuthorityVerifyRoute
  '/_authenticated/business/certificates': typeof AuthenticatedBusinessCertificatesRoute
  '/_authenticated/business/dashboard': typeof AuthenticatedBusinessDashboardRoute
  '/_authenticated/business/instruments': typeof AuthenticatedBusinessInstrumentsRoute
  '/_authenticated/business/notifications': typeof AuthenticatedBusinessNotificationsRoute
  '/_authenticated/business/profile': typeof AuthenticatedBusinessProfileRoute
  '/_authenticated/business/requests': typeof AuthenticatedBusinessRequestsRoute
  '/_authenticated/lmo/smart-route': typeof AuthenticatedLmoSmartRouteRoute
  '/_authenticated/authority/': typeof AuthenticatedAuthorityIndexRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/help'
    | '/authority'
    | '/business'
    | '/lmo'
    | '/onboarding'
    | '/verify/$code'
    | '/verify/'
    | '/authority/assignments'
    | '/authority/certificates'
    | '/authority/dashboard'
    | '/authority/notifications'
    | '/authority/profile'
    | '/authority/queue'
    | '/authority/smart-route'
    | '/authority/verify'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/instruments'
    | '/business/notifications'
    | '/business/profile'
    | '/business/requests'
    | '/lmo/smart-route'
    | '/authority/'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/help'
    | '/lmo'
    | '/onboarding'
    | '/verify/$code'
    | '/verify'
    | '/authority/assignments'
    | '/authority/certificates'
    | '/authority/dashboard'
    | '/authority/notifications'
    | '/authority/profile'
    | '/authority/queue'
    | '/authority/smart-route'
    | '/authority/verify'
    | '/business/certificates'
    | '/business/dashboard'
    | '/business/instruments'
    | '/business/notifications'
    | '/business/profile'
    | '/business/requests'
    | '/lmo/smart-route'
    | '/authority'
    | '/business'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/help'
    | '/_authenticated/authority'
    | '/_authenticated/business'
    | '/_authenticated/lmo'
    | '/_authenticated/onboarding'
    | '/verify/$code'
    | '/verify/'
    | '/_authenticated/authority/assignments'
    | '/_authenticated/authority/certificates'
    | '/_authenticated/authority/dashboard'
    | '/_authenticated/authority/notifications'
    | '/_authenticated/authority/profile'
    | '/_authenticated/authority/queue'
    | '/_authenticated/authority/smart-route'
    | '/_authenticated/authority/verify'
    | '/_authenticated/business/certificates'
    | '/_authenticated/business/dashboard'
    | '/_authenticated/business/instruments'
    | '/_authenticated/business/notifications'
    | '/_authenticated/business/profile'
    | '/_authenticated/business/requests'
    | '/_authenticated/lmo/smart-route'
    | '/_authenticated/authority/'
    | '/_authenticated/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authority': {
      id: '/_authenticated/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthenticatedAuthorityRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lmo': {
      id: '/_authenticated/lmo'
      path: '/lmo'
      fullPath: '/lmo'
      preLoaderRoute: typeof AuthenticatedLmoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authority/': {
      id: '/_authenticated/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthenticatedAuthorityIndexRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/assignments': {
      id: '/_authenticated/authority/assignments'
      path: '/assignments'
      fullPath: '/authority/assignments'
      preLoaderRoute: typeof AuthenticatedAuthorityAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/certificates': {
      id: '/_authenticated/authority/certificates'
      path: '/certificates'
      fullPath: '/authority/certificates'
      preLoaderRoute: typeof AuthenticatedAuthorityCertificatesRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/dashboard': {
      id: '/_authenticated/authority/dashboard'
      path: '/dashboard'
      fullPath: '/authority/dashboard'
      preLoaderRoute: typeof AuthenticatedAuthorityDashboardRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/notifications': {
      id: '/_authenticated/authority/notifications'
      path: '/notifications'
      fullPath: '/authority/notifications'
      preLoaderRoute: typeof AuthenticatedAuthorityNotificationsRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/profile': {
      id: '/_authenticated/authority/profile'
      path: '/profile'
      fullPath: '/authority/profile'
      preLoaderRoute: typeof AuthenticatedAuthorityProfileRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/queue': {
      id: '/_authenticated/authority/queue'
      path: '/queue'
      fullPath: '/authority/queue'
      preLoaderRoute: typeof AuthenticatedAuthorityQueueRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/smart-route': {
      id: '/_authenticated/authority/smart-route'
      path: '/smart-route'
      fullPath: '/authority/smart-route'
      preLoaderRoute: typeof AuthenticatedAuthoritySmartRouteRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/authority/verify': {
      id: '/_authenticated/authority/verify'
      path: '/verify'
      fullPath: '/authority/verify'
      preLoaderRoute: typeof AuthenticatedAuthorityVerifyRouteImport
      parentRoute: typeof AuthenticatedAuthorityRouteRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/certificates': {
      id: '/_authenticated/business/certificates'
      path: '/certificates'
      fullPath: '/business/certificates'
      preLoaderRoute: typeof AuthenticatedBusinessCertificatesRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/dashboard': {
      id: '/_authenticated/business/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof AuthenticatedBusinessDashboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/instruments': {
      id: '/_authenticated/business/instruments'
      path: '/instruments'
      fullPath: '/business/instruments'
      preLoaderRoute: typeof AuthenticatedBusinessInstrumentsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/notifications': {
      id: '/_authenticated/business/notifications'
      path: '/notifications'
      fullPath: '/business/notifications'
      preLoaderRoute: typeof AuthenticatedBusinessNotificationsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/profile': {
      id: '/_authenticated/business/profile'
      path: '/profile'
      fullPath: '/business/profile'
      preLoaderRoute: typeof AuthenticatedBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/requests': {
      id: '/_authenticated/business/requests'
      path: '/requests'
      fullPath: '/business/requests'
      preLoaderRoute: typeof AuthenticatedBusinessRequestsRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/lmo/smart-route': {
      id: '/_authenticated/lmo/smart-route'
      path: '/smart-route'
      fullPath: '/lmo/smart-route'
      preLoaderRoute: typeof AuthenticatedLmoSmartRouteRouteImport
      parentRoute: typeof AuthenticatedLmoRouteRoute
    }
  }
}

interface AuthenticatedAuthorityRouteRouteChildren {
  AuthenticatedAuthorityAssignmentsRoute: typeof AuthenticatedAuthorityAssignmentsRoute
  AuthenticatedAuthorityCertificatesRoute: typeof AuthenticatedAuthorityCertificatesRoute
  AuthenticatedAuthorityDashboardRoute: typeof AuthenticatedAuthorityDashboardRoute
  AuthenticatedAuthorityNotificationsRoute: typeof AuthenticatedAuthorityNotificationsRoute
  AuthenticatedAuthorityProfileRoute: typeof AuthenticatedAuthorityProfileRoute
  AuthenticatedAuthorityQueueRoute: typeof AuthenticatedAuthorityQueueRoute
  AuthenticatedAuthoritySmartRouteRoute: typeof AuthenticatedAuthoritySmartRouteRoute
  AuthenticatedAuthorityVerifyRoute: typeof AuthenticatedAuthorityVerifyRoute
  AuthenticatedAuthorityIndexRoute: typeof AuthenticatedAuthorityIndexRoute
}

const AuthenticatedAuthorityRouteRouteChildren: AuthenticatedAuthorityRouteRouteChildren =
  {
    AuthenticatedAuthorityAssignmentsRoute:
      AuthenticatedAuthorityAssignmentsRoute,
    AuthenticatedAuthorityCertificatesRoute:
      AuthenticatedAuthorityCertificatesRoute,
    AuthenticatedAuthorityDashboardRoute: AuthenticatedAuthorityDashboardRoute,
    AuthenticatedAuthorityNotificationsRoute:
      AuthenticatedAuthorityNotificationsRoute,
    AuthenticatedAuthorityProfileRoute: AuthenticatedAuthorityProfileRoute,
    AuthenticatedAuthorityQueueRoute: AuthenticatedAuthorityQueueRoute,
    AuthenticatedAuthoritySmartRouteRoute:
      AuthenticatedAuthoritySmartRouteRoute,
    AuthenticatedAuthorityVerifyRoute: AuthenticatedAuthorityVerifyRoute,
    AuthenticatedAuthorityIndexRoute: AuthenticatedAuthorityIndexRoute,
  }

const AuthenticatedAuthorityRouteRouteWithChildren =
  AuthenticatedAuthorityRouteRoute._addFileChildren(
    AuthenticatedAuthorityRouteRouteChildren,
  )

interface AuthenticatedBusinessRouteRouteChildren {
  AuthenticatedBusinessCertificatesRoute: typeof AuthenticatedBusinessCertificatesRoute
  AuthenticatedBusinessDashboardRoute: typeof AuthenticatedBusinessDashboardRoute
  AuthenticatedBusinessInstrumentsRoute: typeof AuthenticatedBusinessInstrumentsRoute
  AuthenticatedBusinessNotificationsRoute: typeof AuthenticatedBusinessNotificationsRoute
  AuthenticatedBusinessProfileRoute: typeof AuthenticatedBusinessProfileRoute
  AuthenticatedBusinessRequestsRoute: typeof AuthenticatedBusinessRequestsRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
}

const AuthenticatedBusinessRouteRouteChildren: AuthenticatedBusinessRouteRouteChildren =
  {
    AuthenticatedBusinessCertificatesRoute:
      AuthenticatedBusinessCertificatesRoute,
    AuthenticatedBusinessDashboardRoute: AuthenticatedBusinessDashboardRoute,
    AuthenticatedBusinessInstrumentsRoute:
      AuthenticatedBusinessInstrumentsRoute,
    AuthenticatedBusinessNotificationsRoute:
      AuthenticatedBusinessNotificationsRoute,
    AuthenticatedBusinessProfileRoute: AuthenticatedBusinessProfileRoute,
    AuthenticatedBusinessRequestsRoute: AuthenticatedBusinessRequestsRoute,
    AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
  }

const AuthenticatedBusinessRouteRouteWithChildren =
  AuthenticatedBusinessRouteRoute._addFileChildren(
    AuthenticatedBusinessRouteRouteChildren,
  )

interface AuthenticatedLmoRouteRouteChildren {
  AuthenticatedLmoSmartRouteRoute: typeof AuthenticatedLmoSmartRouteRoute
}

const AuthenticatedLmoRouteRouteChildren: AuthenticatedLmoRouteRouteChildren = {
  AuthenticatedLmoSmartRouteRoute: AuthenticatedLmoSmartRouteRoute,
}

const AuthenticatedLmoRouteRouteWithChildren =
  AuthenticatedLmoRouteRoute._addFileChildren(
    AuthenticatedLmoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuthorityRouteRoute: typeof AuthenticatedAuthorityRouteRouteWithChildren
  AuthenticatedBusinessRouteRoute: typeof AuthenticatedBusinessRouteRouteWithChildren
  AuthenticatedLmoRouteRoute: typeof AuthenticatedLmoRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuthorityRouteRoute:
    AuthenticatedAuthorityRouteRouteWithChildren,
  AuthenticatedBusinessRouteRoute: AuthenticatedBusinessRouteRouteWithChildren,
  AuthenticatedLmoRouteRoute: AuthenticatedLmoRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
